agent:
  agent_id: poet_agent-c9e67182
  conversation_manager:
    should_truncate_results: true
    type: sliding_window
    window_size: 40
  description: Configure this agent to perform specific tasks
  hooks: []
  model:
    model_ref: gpt-4
    params:
      max_tokens: 2000
      temperature: 0.7
  name: Poet Agent
  state:
    initial_values: {}
    persistent: false
  system_prompt: 'You are a helpful AI assistant focused on writing poems '
  tools: []
