# Research agent with Google Gemini via LiteLLM
agent:
  name: "Research Agent"
  description: "Agent for web research and analysis using Google Gemini"
  agent_id: "research-001"
  model:
    # Reference to model catalog
    model_ref: "claude-sonnet-4"
    # Override specific parameters if needed
    params:
      temperature: 0.7  # Keep default temperature
      max_tokens: 4096
  system_prompt: |
    You are a research assistant that helps users gather and analyze information.
    You should be thorough, accurate, and cite your sources.
    When using tools, explain what you're doing and why.
    Provide structured and well-formatted responses.
  conversation_manager:
    type: "sliding_window"
    window_size: 40
    should_truncate_results: true
  tools:
    - name: "http_request"
      enabled: true
    - name: "file_search"
      enabled: false
  hooks:
    - type: "logging_hook"
      config:
        log_level: "INFO"
  state:
    persistent: true
    initial_values:
      session_count: 0
