workflow_id: debug-workflow
name: Debug Workflow
description: Debug agent creation
version: 1.0.0
topology: sequential
nodes: []
edges: []
entry_points: null
communication: []
context:
  shared_keys:
  - workflow_input
  - workflow_context
  node_specific_keys: {}
  persistence: true
  isolation_level: workflow
parallel_config: null
max_execution_time: 1800
error_handling: stop
tags: []
created_at: 2025-09-13 22:18:23.753293
updated_at: 2025-09-13 22:18:23.753298
